CREATE TABLE `MIG_TBL_INFO` (
  `TABLE_OWNER` varchar(30) NOT NULL COMMENT '테이블OWNER(PK1)',
  `TABLE_ID` varchar(30) NOT NULL COMMENT '테이블ID(PK2)',
  `PROC_ORD` decimal(5,0) NOT NULL COMMENT '처리순서(PK3)',
  `TASK_ID` varchar(30) DEFAULT NULL COMMENT '작업ID',
  `SRC_DB_PREFIX` varchar(10) NOT NULL COMMENT '추출원천 데이터베이스',
  `TGT_DB_PREFIX` varchar(10) NOT NULL COMMENT '적재대상 데이터베이스',
  `MIG_LOAD_MODE` char(1) NOT NULL DEFAULT 'T' COMMENT '이행적재모드. (테이블 적재시 Truncate/Append 여부)',
  `LOB_YN` char(1) NOT NULL DEFAULT 'N' COMMENT 'LOB여부. Y=LOB(BLOB/CLOB/BINARY/IMAGE) 컬럼 보유 N=일반(기본)',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `MNGR_ID` varchar(20) DEFAULT NULL COMMENT '담당자 ID',
  `TABLE_NM` varchar(100) NOT NULL,
  `MIG_COND` varchar(4000) DEFAULT NULL COMMENT '이관조건 (WHERE절 본문, 키워드 제외. 공란=전체 추출)',
  `BIZ_AREA_CD` varchar(30) DEFAULT NULL COMMENT '업무영역코드 (DW/경영정보/여신IT)',
  `SUBJ_AREA_CD` varchar(30) DEFAULT NULL COMMENT '주제영역코드 (고객/계좌/거래/상품/채널/공통코드)',
  `GRP1_CD` varchar(30) DEFAULT NULL COMMENT '그룹1코드',
  `GRP2_CD` varchar(30) DEFAULT NULL COMMENT '그룹2코드',
  `GRP3_CD` varchar(30) DEFAULT NULL COMMENT '그룹3코드',
  `GRP4_CD` varchar(30) DEFAULT NULL COMMENT '그룹4코드',
  `GRP5_CD` varchar(30) DEFAULT NULL COMMENT '그룹5코드',
  `REG_ID` varchar(20) DEFAULT NULL COMMENT '등록자',
  `REG_DTM` datetime DEFAULT current_timestamp() COMMENT '등록일시',
  `LST_ADJPRN_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자',
  `LST_ADJ_DTM` datetime DEFAULT current_timestamp() COMMENT '최종수정일시',
  PRIMARY KEY (`TABLE_OWNER`,`TABLE_ID`,`PROC_ORD`),
  KEY `IX_MIG_TBL_INFO_01` (`MNGR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='이관대상 테이블속성 관리';
